export default [
    { id: "1", name: '才子', parentId: "0", order: 1 },
    { id: "2", name: '佳人', parentId: "0", order: 2 },
    { id: "3", name: '东', parentId: "1", order: 1 },
    { id: "4", name: '西', parentId: "1", order: 2 },
    { id: "5", name: '南', parentId: "1", order: 3 },
    { id: "6", name: '北', parentId: "1", order: 4 },
    { id: "7", name: '东', parentId: "2", order: 1 },
    { id: "8", name: '西', parentId: "2", order: 2 },
    { id: "9", name: '南', parentId: "2", order: 3 },
    { id: "10", name: '北', parentId: "2", order: 4 },
    { id: "11", name: '才子我啊', parentId: "3", order: 1 },
    { id: "12", name: '才子我呀', parentId: "4", order: 1 },
    { id: "13", name: '才子我拉', parentId: "3", order: 2 },
    { id: "14", name: '才子我哈', parentId: "4", order: 2 },
]